### PR TITLE
feat: DATA-11968 Update Generative model to latest version

### PR DESCRIPTION
**Pull request by bc-rmalyavc**
## What & Why?  [DATA-11968](https://bigcommercecloud.atlassian.net/browse/DATA-11968)
- Switch to `@google-cloud/vertexai` sdk in order to use latest models
- Use the latest generative model `gemini-1.5-pro-001`
- Update related env variables and authentication sequence as per new sdk requirements
- Update `README` to reflect changes in authentication process

## Testing / Proof
- Manually in dev mode.
    - Created a service account as per step 8 in `README`
    - Created a draft app in `BigCommerce` dev portal and directed it the app run locally via ngrok (see README)
    - Verified that the the app is working and is able to generate descriptions for the product. 
- Manually on preview app (In progress)
    - Deployed the changes to Preview environment on Vercel
    - Created a service account as per step 8 in `README`
    - Created a new env variable `GOOGLE_SERVICE_ACCOUNT_JSON_BASE64` in Preview env and pasted the base64 encoded account details as a value for it.
    - Created another draft app and directed it to the app deployed in `Preview` env.
    - Installed the draft app to a sandbox store and verified that it is working and is able to generate description for the product
    
image

**Some other examples of the old vs new model**
 
**The old model fails to generate the description in humorous style as requeted**
Screenshot 2024-08-01 at 17 40 17

**The new model successfully returns a humorous description**
Screenshot 2024-08-01 at 17 39 28

@bigcommerce/team-data

[DATA-11968]: https://bigcommercecloud.atlassian.net/browse/DATA-11968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by solofeed — APPROVED** [review]
LGTM!

**Comment by solofeed** [comment]
Let's not merge until we get a service account for a vertex AI

I will comment on it here

**Review by bc-prestonhuth — CHANGES_REQUESTED** [review]
This PR needs clear evidence of what was tested and how. It also needs a clear deployment plan. Specifically, what steps need to be taken to configure the service account properly? It would help to point out the documentation that was linked in the README from the PR description so it is clear what steps are being followed.

Please update the PR template as well to match [here](https://github.com/bigcommerce/documentation/blob/b70b3587de78cfe1f8186f87bb5c953ee13cfa73/content/process/repositories/pull-request-templates.md).

**Review by bc-prestonhuth — CHANGES_REQUESTED** [review]
I'm still not seeing anything convincing me that this change is well tested and safe to deploy OR that the intended change was achieved. Is there a way to prove that we are now hitting the latest version of the model?

**Comment by bc-rmalyavc** [comment]
> I'm still not seeing anything convincing me that this change is well tested and safe to deploy OR that the intended change was achieved. Is there a way to prove that we are now hitting the latest version of the model?

@bc-prestonhuth,
I have updated the `testing` section in the PR description. Listed all steps we performed to make sure that the change is safe to deploy. Also updated the PR template as you requested.

`Is there a way to prove that we are now hitting the latest version of the model?`
We were able to see the endpoint hit in the console in Vercel. Perhaps, @solofeed can share some screenshots if you feel you need to see them

`OR that the intended change was achieved`
The intended change was to improve the quality of descriptions generated by switching to the latest model. I'm not sure we can really prove it. Though, as per the screenshot I posted you can see that it started adding emoji) I believe it didn't previously

**Review by bc-prestonhuth — APPROVED** [review]

**Pull request merged**
